apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: chalkular
    app.kubernetes.io/managed-by: kustomize
  name: artifacts
  namespace: system
spec:
  ports:
  - name: https
    port: 7443
    protocol: TCP
    targetPort: 7443
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: chalkular
