resources:
- manager.yaml
- artifacts_service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
configMapGenerator:
- name: controller-manager-config
  options:
    disableNameSuffixHash: true
