# This rule is not used by the project chalkular itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over chalkular.ocular.crashoverride.run.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: chalkular
    app.kubernetes.io/managed-by: kustomize
  name: artifactmediatypemapping-admin-role
rules:
- apiGroups:
  - chalkular.ocular.crashoverride.run
  resources:
  - artifactmediatypemappings
  verbs:
  - '*'
- apiGroups:
  - chalkular.ocular.crashoverride.run
  resources:
  - artifactmediatypemappings/status
  verbs:
  - get
