# This rule is not used by the project chalkular itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the chalk.ocular.crashoverride.run.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: chalkular
    app.kubernetes.io/managed-by: kustomize
  name: mediatypepolicy-editor-role
rules:
- apiGroups:
  - chalk.ocular.crashoverride.run
  resources:
  - mediatypepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chalk.ocular.crashoverride.run
  resources:
  - mediatypepolicies/status
  verbs:
  - get
