apiVersion: chalkular.ocular.crashoverride.run/v1beta1
kind: ArtifactMediaTypeMapping
metadata:
  labels:
    app.kubernetes.io/name: chalkular
    app.kubernetes.io/managed-by: kustomize
  name: artifactmediatypemapping-sample
spec:
  # TODO(user): Add fields here
