apiVersion: chalk.ocular.crashoverride.run/v1beta1
kind: MediaTypePolicy
metadata:
  labels:
    app.kubernetes.io/name: chalkular
    app.kubernetes.io/managed-by: kustomize
  name: mediatypepolicy-sample
spec:
  # TODO(user): Add fields here
